# Generated by Django 2.1 on 2019-05-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('imagen', models.ImageField(blank=True, upload_to='productos/%Y/%m/%d', verbose_name='imágen')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('stock', models.PositiveIntegerField(verbose_name='stock')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
